name: trino_showcase
version: "0.1.0"
profile: trino_showcase

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests/dbt"]

models:
  trino_showcase:
    +materialized: view
    staging:
      +schema: staging
    canonical:
      +schema: canonical
    marts:
      +schema: marts
    semantic:
      +schema: semantic
